// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewBook struct {
	Name      string `json:"name"`
	Isbn      int    `json:"ISBN"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}
